server:
  port: 8888
spring:
  rabbitmq:
    host: 192.168.116.132
    port: 5672
    username: admin
    password: 20170440
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
